function [lat,long,speed,alt,time,svid] = loadRunData(path)
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/leila/Desktop/GPS Project/Spreadsheets/Run1_2-01.xlsx
%    Worksheet: UsableData
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/02/17 14:52:44

%% Import the data
[~, ~, raw] = xlsread(path,'UsableData');
raw = raw(2:end,:);
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
Run1201S1 = table;

%% Allocate imported array to column variable names
svid = categorical(stringVectors(:,1));
lat = data(:,1);
long = data(:,2);
alt = data(:,3);
speed = data(:,4);
time = data(:,5);

%% Clear temporary variables
clearvars data raw stringVectors;
end